@startuml
|教务处|
:安排考试;
:考试安排表;
|教师|
:出卷;
fork
:A、B试卷;
fork again
|教师|
:打印审批表;
|系主任|
:审批签字;
:打印审批表;
end fork
|教务处|
:打印试卷;
:试卷;
|学生|
:参加考试;
:答卷;
|教师|
:阅卷出成绩;
fork
:答卷;
:装订存档;
fork again
:成绩单;
|教务处|
if(有不及格？)then(有)
:安排补考;
fork
:补考安排表;
fork again
end fork
else(无)
end
endif
end fork
|教师|
:期末流程结束;
stop
@enduml
