@startuml
class Person {
  String Name
  String Sex
  int Age
  String Number
  String address
  String Email
}
class Library_Admin {
  String Library_Admin_ID
  Boolean Library_Admin_AddBookInfo()
  Boolean Library_Admin_DeleteBookInfo()
  Boolean Library_Admin_UpdateBookInfo()
  Boolean Library_Admin_SelectBookInfo()
  Boolean Library_Admin_LendBook()Boolean
  Boolean Library_Admin_ReturnBook()
  Boolean Library_Admin_SelectReaderState()
}
class InfoManager {
  String InfoManager_ID
  Boolean InfoManager_AddReaderInfo()
  Boolean InfoManager_DeleteReaderInfo()
  Boolean InfoManager_UpdateReaderInfo()
  Boolean InfoManager_SelectReaderInfo()
  Boolean InfoManager_AddLibrary_AdminInfo()
  Boolean InfoManager_DeleteLibrary_AdminInfo()
  Boolean InfoManager_UpdateLibrary_AdminInfo()
  Boolean InfoManager_SelectLibrary_AdminInfo()
}
class Reader {
  String Reader_ID
  String State
  String SelectState()
  Book SelectBook()
  Boolean BorrowBook()
  Boolean BackBook()
  Boolean LateApplication()
  Boolean CompensationBook()
}
class Book {
  String ISBA
  String Name
  String Category
  String Publisher
  String Published-Date
}
Person <|-- Library_Admin
Person <|-- InfoManager
Person <|-- Reader


Book - "*"预定记录:被预定
Library_Admin"*" - "1"InfoManager:授权
Reader"*" - "1"Library_Admin:注册
Reader"1" - "*"预定记录
Reader--借书记录
Reader--还书记录
借书记录"1" -- "0.1"逾期记录
借书记录"*" - "1"Library_Admin:登记

逾期记录"*" - "0.1"罚款细则:使用

class 预定记录{
预定日期
}
class 借书记录{
借书日期
归还日期
}
class 还书记录{
归还日期
}
class 逾期记录{
逾期天数
}

class 罚款细则{
}


@enduml