@startuml
actor 图书管理员
participant ":信息系统"
actor 读者
activate 读者
participant ":借阅记录"
读者 -> 图书管理员:归还图书,提交个人信息
loop
deactivate 读者
activate ":借阅记录"
activate 图书管理员
图书管理员 --> ":借阅记录":提交读者信息
":借阅记录" --> 图书管理员 :反馈借阅信息
图书管理员 --> 读者:验证借阅信息:False ,提交无可还书信息
图书管理员 -->":信息系统":验证借阅信息:True ,提交还书信息
activate ":信息系统"
":信息系统" --> ":信息系统":验证还书信息
":信息系统" -> 图书管理员: True
end
图书管理员 -> ":借阅记录":验证成功，更新借阅信息
@enduml