@startuml
actor "读者"
participant "信息系统"
activate "读者"
"读者" -> "信息系统":登录
activate "信息系统"
"信息系统" -> "信息系统":验证读\n者信息
alt successful case

	"信息系统" ->"读者":登录成功
	"读者" ->o "修改信息"
	note right
	修改信息包括：
    	修改个人信息
    	预定图书记录
    	查看自己的借书记录
    	查看所借图书归还日期
    end note
	activate "修改信息"
alt 归还图书
"归还图书" ->o "读者":提示读者确认书本完整并按时还书
"读者"->"信息系统":提交所还图书的信息
else 偿还图书
"读者" ->"信息系统":提交损失图书信息
"信息系统"->"读者":反馈读者赔偿信息
end
else failure case

	"信息系统" ->"读者": 提示正确输入登录信息
	loop 3 times
   "读者" -> "读者":检查自\n己的登\n录信息
   "读者" -> "信息系统":再次登录
   note right
   三次登录失败后锁定账号无法再次登录
   可寻求管理员解锁
       end note
   end
end
@enduml