@startuml
actor 图书管理员
participant 信息系统
actor 读者
读者 --> 信息系统:预定图书
activate 信息系统
信息系统 --> 读者:有图书则通知读者借阅
activate 读者
读者 -> 图书管理员:将借书信息以及个人信息提供给图书管理员
activate 图书管理员
图书管理员 --> 信息系统:提交借书信息以及读者个人信息给系统
信息系统 --> 图书管理员:将当前图书信息以及是否有不良借阅信息反馈给图书管理员
图书管理员 -> 读者:将验证结果反馈给读者，如结果成立，则允许读者借书；否则不允许读者借阅
@enduml