@startuml
actor 信息管理员
actor 图书管理员
participant ":信息系统"
activate 信息管理员
信息管理员 -> ":信息系统":登录
activate ":信息系统"
":信息系统" -> ":信息系统":验证信息管理员\n信息
alt 信息管理员

	":信息系统" ->信息管理员:登录成功
	信息管理员 ->o ":管理信息操作"
	note right
	管理信息包括：
    	修改管理员个人信息
    	修改图书管理员信息
    	查阅图书记录
    	查看图书管理员记录
    end note
	activate ":信息管理"
alt 图书管理员
activate 图书管理员
图书管理员 -> ":信息系统":登录
":信息系统" -> ":信息系统":验证图书管理员\n信息
":信息系统" ->图书管理员:登录成功
图书管理员 ->o ":书籍信息操作"
note right
	书籍信息操作包括：
    	添加书籍信息
    	更新书籍信息
    	删除书籍信息
    	查阅书籍信息
    end note
图书管理员 ->o ":用户信息操作"
note right
	用户信息操作包括：
    	添加用户信息
    	更新用户信息
    	删除用户信息
    	查看用户基本信息
    	验证用户借阅信息
    end note
end
end
@enduml